#pragma config(Sensor, in2,    lineFollow,     sensorLineFollower)
#pragma config(Sensor, dgtl4,  buttonMain,     sensorTouch)
#pragma config(Motor,  port5,           servoArm2,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           servoArm,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           flashLight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port8,           convBelt,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*void openClose(){
	setServo(port6, 0);
	wait(1);
	setServo(port6, 53);
}*/

void goFast(){
	setServo(port6, 65);
	wait(.5);
	setServo(port6, 0);
	wait(.5);
	setServo(port6, 63);
}

task main(){
	int count = 0;
		while(1==1){
				setServo(port6, 63);
				setServo(port5, -50);
			while(SensorValue[buttonMain]==1){
				while(count < 15){
					//--------------------------
					setServo(port5, -80);
						waitInMilliseconds(120);
					setServo(port5, -50);
						//waitInMilliseconds(480);
						//stopMotor(port5);
					//---------------------------
					//decision();
					//wait(2);
					//2180-2250 white plastic
					//2160-2190 brown plastic
					//1910-2490 wooden
					//2870-2910 clear

					wait(3);
	if(SensorValue(lineFollow)>2855 && SensorValue(lineFollow)<2885){ //clear marble left1
		startMotor(convBelt, 28);
			wait(1.3);
		stopMotor(convBelt);
		goFast();
			wait(2.5);
		startMotor(convBelt, -33);
			wait(1.3);
			stopMotor(convBelt);

	}else if(SensorValue(lineFollow)>2740 && SensorValue(lineFollow)<2810){ //brown plastic left2
		startMotor(convBelt, 28);
			wait(.8);
		stopMotor(convBelt);
		goFast();
			wait(2.5);
		startMotor(convBelt, -32);
			wait(.7);
			stopMotor(convBelt);

	}else if(SensorValue(lineFollow)>2000 && SensorValue(lineFollow)<2070){ //white plastic right2
		startMotor(convBelt, -26);
			wait(0.8);
		stopMotor(convBelt);
		goFast();
			wait(2.5);
		startMotor(convBelt, 26);
			wait(0.9);
			stopMotor(convBelt);

	}else if(SensorValue(lineFollow)>2150 && SensorValue(lineFollow)<2490){ //wood right1
		startMotor(convBelt, -29);
			wait(1.2);
		stopMotor(convBelt);
		goFast();
			wait(2.5);
		startMotor(convBelt, 28);
			wait(1.4);
			stopMotor(convBelt);

	}//if(SensorValue(lineFollow)>2344 && SensorValue(lineFollow)<2334){ //metal marble
	else{
		goFast();
	}//end if
				wait(2);

			}//end while count
		}//end while button
	}//end infinite
}//end main
